import { useEffect, useMemo, useRef, useState } from 'react'
import { AnimatePresence, motion, useScroll, useTransform } from 'motion/react'
import { ArrowDown, ArrowLeft, ArrowRight, Check, Heart, Menu, Minus, Plus, RotateCcw, Search, ShoppingBag, SlidersHorizontal, Sparkles, X } from 'lucide-react'
import WatchVisual from './WatchVisual'
import MotionEditorial from './MotionEditorial'
import ProductPage from './ProductPage'
import StrapCatalog from './StrapCatalog'
import StrapPage from './StrapPage'
import StrapVisual from './StrapVisual'
import { money, slugOf, strapFromPath, straps, watchFromPath, watches, type Strap, type Watch } from './data'

type Category = 'Todos' | Watch['category']
const categories: Category[] = ['Todos', 'Clássicos', 'Esportivos', 'Minimalistas', 'Mergulho', 'Cronógrafos', 'Campo', 'GMT']
type CartLine = { product: Watch | Strap; quantity: number; width?: number }
const isStrap = (product: Watch | Strap): product is Strap => 'material' in product

function App() {
  const storyRef = useRef<HTMLElement>(null)
  const reducedMotion = false
  const [intro, setIntro] = useState(() => window.location.pathname === '/')
  const { scrollYProgress } = useScroll()
  const { scrollYProgress: storyProgress } = useScroll({ target: storyRef, offset: ['start end', 'end start'] })
  const heroDrift = useTransform(scrollYProgress, [0, .16], [0, -110])
  const storyTurn = useTransform(storyProgress, [0, 1], [-35, 325])
  const storyLift = useTransform(storyProgress, [0, .5, 1], [85, 0, -85])
  const storyFirstOpacity = useTransform(storyProgress, [.08, .35, .52], [0, 1, 0])
  const storySecondOpacity = useTransform(storyProgress, [.45, .67, .88], [0, 1, 0])
  const [category, setCategory] = useState<Category>('Todos')
  const [query, setQuery] = useState('')
  const [searchOpen, setSearchOpen] = useState(false)
  const [menuOpen, setMenuOpen] = useState(false)
  const [cartOpen, setCartOpen] = useState(false)
  const [cart, setCart] = useState<Record<string, CartLine>>({})
  const [favorites, setFavorites] = useState<number[]>([])
  const [productId, setProductId] = useState(() => watchFromPath(window.location.pathname)?.id ?? null)
  const [strapId, setStrapId] = useState(() => strapFromPath(window.location.pathname)?.id ?? null)
  const [strapsListing, setStrapsListing] = useState(() => window.location.pathname === '/pulseiras')
  const [heroIndex, setHeroIndex] = useState(0)
  const [toast, setToast] = useState('')
  const hero = [watches[1], watches[0], watches[2]][heroIndex]
  const filtered = useMemo(() => watches.filter(w => (category === 'Todos' || w.category === category) && `${w.name} ${w.collection} ${w.category}`.toLowerCase().includes(query.toLowerCase())), [category, query])
  const cartCount = Object.values(cart).reduce((sum, line) => sum + line.quantity, 0)
  const cartTotal = Object.values(cart).reduce((sum, line) => sum + line.product.price * line.quantity, 0)
  useEffect(() => { if (!toast) return; const t = window.setTimeout(() => setToast(''), 2800); return () => window.clearTimeout(t) }, [toast])
  useEffect(() => { if (!intro) return; const t = window.setTimeout(() => setIntro(false), 2800); return () => window.clearTimeout(t) }, [intro])
  useEffect(() => { const lock = cartOpen || menuOpen; document.body.style.overflow = lock ? 'hidden' : ''; return () => { document.body.style.overflow = '' } }, [cartOpen, menuOpen])
  useEffect(() => { const onPopState = () => { setProductId(watchFromPath(window.location.pathname)?.id ?? null); setStrapId(strapFromPath(window.location.pathname)?.id ?? null); setStrapsListing(window.location.pathname === '/pulseiras'); window.scrollTo(0, 0) }; window.addEventListener('popstate', onPopState); return () => window.removeEventListener('popstate', onPopState) }, [])
  useEffect(() => { document.title = productId ? `${watches.find(watch => watch.id === productId)?.name ?? 'Relógio'} | AUREL` : strapId ? `${straps.find(strap => strap.id === strapId)?.name ?? 'Pulseira'} | AUREL` : strapsListing ? 'Pulseiras | AUREL' : 'AUREL — O tempo em sua melhor forma' }, [productId, strapId, strapsListing])
  const add = (product: Watch | Strap, quantity = 1, width?: number) => { const key = isStrap(product) ? `strap-${product.id}-${width ?? product.widths[0]}` : `watch-${product.id}`; setCart(prev => ({ ...prev, [key]: { product, width, quantity: (prev[key]?.quantity ?? 0) + quantity } })); setToast(`${product.name} adicionado à sacola`) }
  const changeQty = (key: string, change: number) => setCart(prev => { const next = { ...prev }; const quantity = (next[key]?.quantity ?? 0) + change; if (quantity <= 0) delete next[key]; else next[key] = { ...next[key], quantity }; return next })
  const toggleFavorite = (id: number) => setFavorites(prev => prev.includes(id) ? prev.filter(x => x !== id) : [...prev, id])
  const openProduct = (watch: Watch) => { window.history.pushState({}, '', `/relogios/${slugOf(watch)}`); setProductId(watch.id); setStrapId(null); setStrapsListing(false); window.scrollTo(0, 0) }
  const goStraps = () => { setMenuOpen(false); setSearchOpen(false); window.history.pushState({}, '', '/pulseiras'); setProductId(null); setStrapId(null); setStrapsListing(true); window.scrollTo(0, 0) }
  const openStrap = (strap: Strap) => { window.history.pushState({}, '', `/pulseiras/${slugOf(strap)}`); setProductId(null); setStrapId(strap.id); setStrapsListing(false); window.scrollTo(0, 0) }
  const goHome = (section = 'colecao') => { window.history.pushState({}, '', '/'); setProductId(null); setStrapId(null); setStrapsListing(false); window.setTimeout(() => section === 'top' ? window.scrollTo({ top: 0, behavior: 'smooth' }) : document.getElementById(section)?.scrollIntoView({ behavior: 'smooth' }), 0) }
  const scrollTo = (id: string) => { setMenuOpen(false); if (productId || strapId || strapsListing) { goHome(id); return } document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }) }
  return <>
    <AnimatePresence>{intro && <motion.div className="intro-screen" initial={{ opacity: 1 }} exit={{ opacity: 0, transition: { duration: .75, ease: 'easeInOut' } }} aria-label="Apresentação Aurel"><div className="intro-ring intro-ring-one"/><div className="intro-ring intro-ring-two"/><motion.div className="intro-watch" initial={{ opacity: 0, scale: .52, rotateY: -180, rotateZ: -24 }} animate={{ opacity: 1, scale: 1, rotateY: 360, rotateZ: -14 }} transition={{ duration: 2.25, ease: [ .2, .65, .16, 1 ] }}><WatchVisual watch={watches[1]} large/></motion.div><motion.div className="intro-wordmark" initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .55, duration: .8 }}>AUREL<span>✦</span><small>O TEMPO EM SUA MELHOR FORMA</small></motion.div><div className="intro-bottom"><span>UMA NOVA PERSPECTIVA SOBRE O TEMPO</span></div><div className="intro-progress"/></motion.div>}</AnimatePresence>
    {!reducedMotion && <motion.div className="scroll-progress" style={{ scaleX: scrollYProgress }} aria-hidden="true"/>}
    <div className="announcement">Frete grátis para todo o Brasil em pedidos acima de R$ 500 <span>↗</span></div>
    <header className="header"><button className="mobile-menu icon-button" aria-label="Abrir menu" onClick={() => setMenuOpen(true)}><Menu size={22}/></button><button className="brand" onClick={() => (productId || strapId || strapsListing) ? goHome('top') : window.scrollTo({ top: 0, behavior: 'smooth' })}>AUREL<span className="brand-spark">✦</span></button><nav className="nav-links" aria-label="Navegação principal"><button onClick={() => scrollTo('colecao')}>Relógios</button><button onClick={goStraps}>Pulseiras</button><button onClick={() => scrollTo('editorial')}>Em movimento</button><button onClick={() => scrollTo('manifesto')}>Nossa essência</button><button onClick={() => scrollTo('experiencia')}>Experiência Aurel</button></nav><div className="header-actions"><button className="icon-button search-trigger" aria-label="Buscar relógios" onClick={() => setSearchOpen(v => !v)}><Search size={20}/></button><button className="icon-button" aria-label={`Abrir sacola com ${cartCount} itens`} onClick={() => setCartOpen(true)}><ShoppingBag size={20}/>{cartCount > 0 && <span className="bag-count">{cartCount}</span>}</button></div></header>
    <AnimatePresence>{searchOpen && <motion.div className="search-bar" initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}}><Search size={19}/><input autoFocus placeholder="Encontre o seu próximo relógio..." value={query} onChange={e => { setQuery(e.target.value); scrollTo('colecao') }}/><button aria-label="Fechar busca" onClick={() => {setSearchOpen(false);setQuery('')}}><X size={19}/></button></motion.div>}</AnimatePresence>
    <main>{productId ? <ProductPage key={productId} watch={watches.find(watch => watch.id === productId)!} favorite={favorites.includes(productId)} onFavorite={toggleFavorite} onAdd={(watch, quantity) => { add(watch, quantity); setCartOpen(true) }} onBack={() => goHome()} onOpenProduct={openProduct} /> : strapId ? <StrapPage key={strapId} strap={straps.find(strap => strap.id === strapId)!} onBack={goStraps} onOpen={openStrap} onAdd={(strap, quantity, width) => { add(strap, quantity, width); setCartOpen(true) }} /> : strapsListing ? <StrapCatalog onOpen={openStrap} onAdd={(strap, width) => add(strap, 1, width)} /> : <>
      <section className="hero"><div className="hero-grain"/><div className="hero-type-ghost" aria-hidden="true"><span>TIME</span><span>MATTERS.</span></div><div className="hero-edition">AUREL / 001 &nbsp; — &nbsp; O TEMPO COMO EXPRESSÃO</div><div className="hero-content"><motion.div initial={{opacity:0,y:22}} animate={{opacity:1,y:0}} transition={{duration:.7}}><p className="eyebrow"><span className="eyebrow-line"/> O extraordinário está nos detalhes</p><h1>O tempo em<br/><em>sua melhor</em><br/>forma<span className="period">.</span></h1><p className="hero-copy">Peças que transcendem as horas. Uma curadoria para quem vive cada instante com propósito.</p><div className="hero-ctas"><button className="button button-light" onClick={() => scrollTo('colecao')}>Explorar coleção <ArrowRight size={18}/></button><button className="replay-intro" onClick={() => {window.scrollTo({top:0,behavior:'smooth'});setIntro(true)}}><RotateCcw size={16}/> Rever abertura</button></div></motion.div><div className="hero-bottom"><span>01 / 03 &nbsp;—&nbsp; {hero.collection}</span><button onClick={() => scrollTo('colecao')} aria-label="Ir para coleção"><ArrowDown size={19}/></button></div></div><div className="hero-visual"><div className="hero-orbit orbit-one"/><div className="hero-orbit orbit-two"/><span className="hero-side-label">DESIGNED TO LAST FOREVER · EST. 2026</span><AnimatePresence mode="wait"><motion.div key={hero.id} className="hero-watch" style={reducedMotion ? undefined : { y: heroDrift }} initial={{opacity:0,scale:.86,rotate:-8}} animate={{opacity:1,scale:1,rotate:0}} exit={{opacity:0,scale:1.08,rotate:8}} transition={{duration:.6}}><WatchVisual watch={hero} large/></motion.div></AnimatePresence><div className="hero-product-info"><div><span>EM DESTAQUE</span><h3>{hero.name}</h3><p>{hero.description}</p></div><div className="hero-switch"><button aria-label="Relógio anterior" onClick={() => setHeroIndex(i => (i+2)%3)}><ArrowLeft size={19}/></button><button aria-label="Próximo relógio" onClick={() => setHeroIndex(i => (i+1)%3)}><ArrowRight size={19}/></button></div></div></div><div className="hero-bottom-rail" aria-hidden="true"><span>EST. MMXXVI</span><span>PRECISÃO&nbsp; ✦ &nbsp;PRESENÇA&nbsp; ✦ &nbsp;PROPÓSITO</span><span>SCROLL TO EXPLORE ↓</span></div></section>
      <div className="trust-strip"><span><Sparkles size={17}/> Curadoria excepcional</span><i/><span>Peças selecionadas a dedo</span><i/><span>Entrega para todo o Brasil</span><i/><span>Experiência além do tempo</span></div>
      <section ref={storyRef} className="scroll-story" aria-label="Uma nova perspectiva sobre o tempo"><div className="story-sticky"><div className="story-track">A FORMA DO TEMPO <span>✦</span> A FORMA DO TEMPO <span>✦</span> A FORMA DO TEMPO</div><div className="story-halo"/><motion.div className="story-object" style={reducedMotion ? undefined : { rotateY: storyTurn, y: storyLift }}><WatchVisual watch={watches[1]} large/></motion.div><motion.div className="story-caption story-caption-left" style={reducedMotion ? undefined : { opacity: storyFirstOpacity }}><span>01 / FORMA</span><h2>Perspectivas<br/><em>que surpreendem.</em></h2></motion.div><motion.div className="story-caption story-caption-right" style={reducedMotion ? undefined : { opacity: storySecondOpacity }}><span>02 / ESSÊNCIA</span><h2>Detalhes que<br/><em>permanecem.</em></h2></motion.div><div className="story-scroll-note">ROLE PARA DESCOBRIR <ArrowDown size={14}/></div></div></section>
      <section id="colecao" className="collection section-wrap"><motion.div className="section-head" initial={{opacity:0,y:42}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.35}} transition={{duration:.85,ease:[.22,1,.36,1]}}><div><p className="eyebrow dark"><span className="eyebrow-line"/> Curadoria Aurel</p><h2>Encontre o relógio<br/>que conta <em>sua história.</em></h2></div><p>Da precisão mecânica à expressão do estilo. Descubra peças feitas para marcar os seus momentos.</p></motion.div><div className="filter-row"><div className="filters" role="group" aria-label="Filtrar por categoria">{categories.map(c => <button key={c} className={category === c ? 'active' : ''} onClick={() => setCategory(c)}>{c}</button>)}</div><span className="result-count"><SlidersHorizontal size={16}/>{filtered.length} peças</span></div><div className="product-grid">{filtered.map((watch, i) => <motion.article className="product-card" key={watch.id} initial={{opacity:0,y:32}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:'-30px'}} transition={{delay:i*.07}}><div className={`product-art art-${watch.tone}`} onClick={() => openProduct(watch)} role="button" tabIndex={0} onKeyDown={e => e.key === 'Enter' && openProduct(watch)} aria-label={`Ver detalhes de ${watch.name}`}><span className="product-tag">{i === 0 ? 'BEST SELLER' : watch.category.toUpperCase()}</span><button className={`favorite ${favorites.includes(watch.id) ? 'is-favorite' : ''}`} aria-label={favorites.includes(watch.id) ? 'Remover dos favoritos' : 'Adicionar aos favoritos'} onClick={e => {e.stopPropagation();toggleFavorite(watch.id)}}><Heart size={20} fill={favorites.includes(watch.id) ? 'currentColor' : 'none'}/></button><WatchVisual watch={watch}/><span className="view-product">Ver detalhes <ArrowRight size={15}/></span></div><div className="product-meta"><div><span>{watch.collection}</span><h3><button className="product-name-link" onClick={() => openProduct(watch)}>{watch.name}</button></h3></div><strong>{money(watch.price)}</strong></div><button className="product-add" onClick={() => add(watch)}>Adicionar à sacola <Plus size={17}/></button></motion.article>)}</div>{filtered.length === 0 && <div className="empty-state">Nenhum relógio encontrado. Experimente outra busca.</div>}</section>
      <section className="strap-promo"><div><p className="eyebrow"><span className="eyebrow-line"/> Uma peça, outras versões</p><h2>Mude a pulseira.<br/><em>Mude o momento.</em></h2><p>Couro, borracha, lona, nylon e malha de aço. Descubra um universo de combinações para o seu relógio.</p><button className="button button-light" onClick={goStraps}>Explorar pulseiras <ArrowRight size={18}/></button></div><div className="strap-promo-art"><StrapVisual strap={straps[0]} large/></div></section>
      <section id="manifesto" className="manifesto"><div className="manifesto-art"><div className="manifesto-circle circle-a"/><div className="manifesto-circle circle-b"/><div className="manifesto-watch"><WatchVisual watch={watches[0]} large/></div><span className="manifesto-number">01 — O VALOR DO TEMPO</span></div><div className="manifesto-copy"><p className="eyebrow"><span className="eyebrow-line"/> Nossa essência</p><h2>Mais que horas.<br/><em>Momentos.</em></h2><p>O tempo é o nosso bem mais precioso. Acreditamos em objetos que carregam histórias, revelam personalidade e transformam o simples ato de olhar as horas em um ritual.</p><p>Por isso, selecionamos cada relógio com um olhar atento ao design, à qualidade e ao que realmente permanece.</p><button className="text-link" onClick={() => scrollTo('colecao')}>Descubra nossa curadoria <ArrowRight size={18}/></button></div></section>
      <MotionEditorial onExplore={openProduct} motionEnabled={true} />
      <section id="experiencia" className="experience section-wrap"><p className="eyebrow dark"><span className="eyebrow-line"/> O jeito Aurel de ser</p><h2>Uma experiência à altura<br/>do <em>seu tempo.</em></h2><div className="experience-grid"><div><span className="experience-num">01 /</span><div className="experience-icon">✦</div><h3>Seleção singular</h3><p>Uma curadoria de peças que une design marcante, qualidade e personalidade.</p></div><div><span className="experience-num">02 /</span><div className="experience-icon">◈</div><h3>Compra sem pressa</h3><p>Descubra detalhes, compare estilos e encontre a peça certa para sua história.</p></div><div><span className="experience-num">03 /</span><div className="experience-icon">↗</div><h3>Para onde você for</h3><p>Uma experiência pensada para acompanhar você, do primeiro olhar à entrega.</p></div></div></section>
      <section className="closing"><div><p className="eyebrow"><span className="eyebrow-line"/> Seu tempo é agora</p><h2>Alguns instantes<br/>merecem ser <em>eternos.</em></h2><button className="button button-light" onClick={() => scrollTo('colecao')}>Encontre o seu Aurel <ArrowRight size={18}/></button></div><img className="closing-image" src="/editorial-watch.png" alt="Relógio de mostrador verde em uma fotografia editorial" /></section>
    </>}</main><footer className="footer"><div className="footer-top"><div><strong>AUREL<span>✦</span></strong><p>O tempo em sua melhor forma.</p></div><div><h4>Explore</h4><button onClick={() => scrollTo('colecao')}>Relógios</button><button onClick={goStraps}>Pulseiras</button><button onClick={() => scrollTo('editorial')}>Em movimento</button><button onClick={() => scrollTo('manifesto')}>Nossa essência</button><button onClick={() => scrollTo('experiencia')}>Experiência</button></div><div><h4>Contato</h4><a href="mailto:contato@aurel.com.br">contato@aurel.com.br</a><span>Brasil</span></div><div className="footer-note">O tempo passa.<br/><em>O estilo permanece.</em></div></div><div className="footer-bottom"><span>© 2026 AUREL. Todos os direitos reservados.</span><span>Feito para quem vive cada segundo.</span></div></footer>
    <AnimatePresence>{menuOpen && <><motion.div className="overlay" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={() => setMenuOpen(false)}/><motion.aside className="mobile-drawer" initial={{x:'-100%'}} animate={{x:0}} exit={{x:'-100%'}}><div className="drawer-head"><strong>AUREL✦</strong><button aria-label="Fechar menu" onClick={() => setMenuOpen(false)}><X/></button></div><button onClick={() => scrollTo('colecao')}>Relógios <ArrowRight/></button><button onClick={goStraps}>Pulseiras <ArrowRight/></button><button onClick={() => scrollTo('editorial')}>Em movimento <ArrowRight/></button><button onClick={() => scrollTo('manifesto')}>Nossa essência <ArrowRight/></button><button onClick={() => scrollTo('experiencia')}>Experiência Aurel <ArrowRight/></button></motion.aside></>}</AnimatePresence>
    <AnimatePresence>{cartOpen && <><motion.div className="overlay" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={() => setCartOpen(false)}/><motion.aside className="cart-drawer" initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}} transition={{type:'tween',duration:.3}}><div className="drawer-head"><div><span>SUA SELEÇÃO</span><h2>Sacola <sup>{cartCount}</sup></h2></div><button aria-label="Fechar sacola" onClick={() => setCartOpen(false)}><X/></button></div><div className="cart-items">{cartCount === 0 ? <div className="cart-empty"><ShoppingBag size={38}/><h3>Sua sacola está vazia</h3><p>Uma grande história começa com a peça certa.</p><button className="button button-dark" onClick={() => {setCartOpen(false);scrollTo('colecao')}}>Explorar coleção <ArrowRight size={17}/></button></div> : Object.entries(cart).map(([key, line]) => <div className="cart-item" key={key}><div className={`cart-art ${isStrap(line.product) ? `strap-art-${line.product.tone}` : `art-${line.product.tone}`}`}>{isStrap(line.product) ? <StrapVisual strap={line.product}/> : <WatchVisual watch={line.product}/>}</div><div><span>{line.product.collection}{line.width ? ` · ${line.width} mm` : ""}</span><h3>{line.product.name}</h3><strong>{money(line.product.price)}</strong><div className="qty"><button aria-label={`Diminuir quantidade de ${line.product.name}`} onClick={() => changeQty(key,-1)}><Minus size={14}/></button><span>{line.quantity}</span><button aria-label={`Aumentar quantidade de ${line.product.name}`} onClick={() => changeQty(key,1)}><Plus size={14}/></button></div></div></div>)}</div>{cartCount > 0 && <div className="cart-footer"><div><span>Subtotal</span><strong>{money(cartTotal)}</strong></div><p>Frete calculado na finalização da compra.</p><button className="button button-dark" onClick={() => setToast('Checkout disponível após a integração com os serviços de pedidos e pagamento.')}>Finalizar compra <ArrowRight size={18}/></button></div>}</motion.aside></>}</AnimatePresence>
    <AnimatePresence>{toast && <motion.div className="toast" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} exit={{opacity:0,y:20}}><Check size={17}/>{toast}</motion.div>}</AnimatePresence>
  </>
}
export default App
