export type Watch = { id: number; name: string; collection: string; category: 'Clássicos' | 'Esportivos' | 'Minimalistas' | 'Mergulho' | 'Cronógrafos' | 'Campo' | 'GMT'; design?: 'diver' | 'chrono' | 'field' | 'gmt'; price: number; tone: string; accent: string; description: string }
export const watches: Watch[] = [
  { id: 1, name: 'Orion Obsidian', collection: 'Coleção Nocturne', category: 'Clássicos', price: 4290, tone: 'black', accent: '#bdb09a', description: 'Precisão e presença em cada detalhe.' },
  { id: 2, name: 'Verde Intenso', collection: 'Coleção Origin', category: 'Minimalistas', price: 3690, tone: 'green', accent: '#607668', description: 'Um clássico contemporâneo de personalidade rara.' },
  { id: 3, name: 'Chronos Steel', collection: 'Coleção Velocity', category: 'Esportivos', price: 5190, tone: 'blue', accent: '#6e8a9e', description: 'Feito para acompanhar cada conquista.' },
  { id: 4, name: 'Solaris Gold', collection: 'Coleção Héritage', category: 'Clássicos', price: 6390, tone: 'cream', accent: '#bd9868', description: 'Elegância atemporal em tons de luz.' },
  { id: 5, name: 'Nox Carbon', collection: 'Coleção Velocity', category: 'Esportivos', price: 4790, tone: 'charcoal', accent: '#6d7477', description: 'Força discreta, engenharia precisa.' },
  { id: 6, name: 'Luna Pearl', collection: 'Coleção Origin', category: 'Minimalistas', price: 3890, tone: 'pearl', accent: '#bcae9c', description: 'Leveza que transforma o cotidiano.' },
  { id: 7, name: 'Maré Profunda', collection: 'Coleção Oceano', category: 'Mergulho', design: 'diver', price: 5490, tone: 'ocean', accent: '#2b8797', description: 'Um mergulhador de presença luminosa e espírito livre.' },
  { id: 8, name: 'Costa Negra', collection: 'Coleção Oceano', category: 'Mergulho', design: 'diver', price: 5690, tone: 'copper', accent: '#bd794d', description: 'Contraste quente para explorar além da superfície.' },
  { id: 9, name: 'Rastro 01', collection: 'Coleção Circuit', category: 'Cronógrafos', design: 'chrono', price: 6290, tone: 'racing', accent: '#c4674e', description: 'A energia das pistas em cada fração de segundo.' },
  { id: 10, name: 'Atlas Areia', collection: 'Coleção Terrene', category: 'Campo', design: 'field', price: 3490, tone: 'sand', accent: '#ad9875', description: 'Leitura essencial para caminhos inesperados.' },
  { id: 11, name: 'Atlas Oliva', collection: 'Coleção Terrene', category: 'Campo', design: 'field', price: 3590, tone: 'olive', accent: '#818a65', description: 'Feito para acompanhar a vida fora do roteiro.' },
  { id: 12, name: 'Meridiano Azul', collection: 'Coleção Horizon', category: 'GMT', design: 'gmt', price: 5890, tone: 'navy', accent: '#537a9b', description: 'Dois fusos, infinitas possibilidades.' },
  { id: 13, name: 'Meridiano Rosé', collection: 'Coleção Horizon', category: 'GMT', design: 'gmt', price: 6090, tone: 'rose', accent: '#b98780', description: 'O mundo ao alcance de um olhar elegante.' },
  { id: 14, name: 'Époque Terracota', collection: 'Coleção Héritage', category: 'Clássicos', price: 4490, tone: 'terracotta', accent: '#ac715b', description: 'Um encontro entre memória e novas perspectivas.' },
]
export const money = (value: number) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL', maximumFractionDigits: 0 }).format(value)
export const slugOf = (product: { name: string }) => product.name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
export const watchFromPath = (pathname: string) => watches.find(watch => pathname === `/relogios/${slugOf(watch)}`) ?? null

type WatchDetail = { story: string; movement: string; caseMaterial: string; strap: string; dial: string; diameter: string; glass: string; waterResistance: string; highlights: string[] }
export const watchDetails: Record<number, WatchDetail> = {
  1: { story: 'Uma peça de presença silenciosa. O mostrador escuro encontra a caixa metálica em um desenho feito para atravessar ocasiões e estilos.', movement: 'Automático', caseMaterial: 'Aço escovado', strap: 'Couro preto', dial: 'Preto profundo', diameter: '40 mm', glass: 'Safira', waterResistance: '5 ATM', highlights: ['Contraste preciso', 'Acabamento escovado', 'Elegância sem excessos'] },
  2: { story: 'O verde profundo revela novas nuances a cada ângulo de luz. Uma interpretação contemporânea do relógio clássico, com proporções equilibradas e personalidade própria.', movement: 'Automático', caseMaterial: 'Aço escovado', strap: 'Couro verde', dial: 'Verde intenso', diameter: '40 mm', glass: 'Safira', waterResistance: '5 ATM', highlights: ['Mostrador expressivo', 'Linhas essenciais', 'Presença atemporal'] },
  3: { story: 'Inspirado pelo ritmo de quem está sempre em movimento. Uma composição de aço e azul que reúne energia, precisão e versatilidade.', movement: 'Automático', caseMaterial: 'Aço polido', strap: 'Couro azul', dial: 'Azul aço', diameter: '42 mm', glass: 'Safira', waterResistance: '10 ATM', highlights: ['Leitura nítida', 'Perfil esportivo', 'Ritmo contemporâneo'] },
  4: { story: 'Tons quentes, reflexos suaves e uma silhueta que nunca sai de cena. Solaris traduz o brilho de ocasiões especiais para todos os dias.', movement: 'Automático', caseMaterial: 'Aço com acabamento dourado', strap: 'Couro marrom', dial: 'Champagne', diameter: '40 mm', glass: 'Safira', waterResistance: '5 ATM', highlights: ['Brilho discreto', 'Paleta acolhedora', 'Clássico renovado'] },
  5: { story: 'Uma leitura mais técnica do tempo. Materiais de aparência robusta e mostrador sóbrio criam uma peça feita para presença e movimento.', movement: 'Automático', caseMaterial: 'Aço grafite', strap: 'Couro preto', dial: 'Grafite', diameter: '42 mm', glass: 'Safira', waterResistance: '10 ATM', highlights: ['Aparência técnica', 'Contraste sutil', 'Estilo versátil'] },
  6: { story: 'Leve no visual, marcante na intenção. Luna Pearl combina tons delicados e desenho simples para acompanhar cada momento com naturalidade.', movement: 'Automático', caseMaterial: 'Aço com acabamento dourado', strap: 'Couro areia', dial: 'Pérola', diameter: '38 mm', glass: 'Safira', waterResistance: '5 ATM', highlights: ['Leveza visual', 'Detalhes delicados', 'Uso cotidiano'] },
  7: { story: 'O azul da água profunda inspira um mostrador de alto contraste e uma moldura marcada para aventuras à beira-mar.', movement: 'Automático', caseMaterial: 'Aço escovado', strap: 'Borracha azul', dial: 'Azul oceano', diameter: '42 mm', glass: 'Safira', waterResistance: '20 ATM', highlights: ['Aro de mergulho', 'Contraste luminoso', 'Perfil robusto'] },
  8: { story: 'Uma interpretação ousada do relógio de mergulho, com tons de cobre e escuro que aquecem sua presença.', movement: 'Automático', caseMaterial: 'Aço com acabamento cobre', strap: 'Borracha preta', dial: 'Preto fosco', diameter: '42 mm', glass: 'Safira', waterResistance: '20 ATM', highlights: ['Aro de mergulho', 'Detalhes em cobre', 'Presença marcante'] },
  9: { story: 'Rastro 01 traduz o pulso das pistas em submostradores e acentos de cor que convidam ao movimento.', movement: 'Quartzo cronógrafo', caseMaterial: 'Aço escovado', strap: 'Couro perfurado', dial: 'Grafite e coral', diameter: '42 mm', glass: 'Safira', waterResistance: '10 ATM', highlights: ['Submostradores', 'Acentos esportivos', 'Leitura dinâmica'] },
  10: { story: 'Os tons de areia e a numeração clara fazem deste relógio de campo um parceiro para dias em movimento.', movement: 'Automático', caseMaterial: 'Aço escovado', strap: 'Lona areia', dial: 'Creme fosco', diameter: '39 mm', glass: 'Safira', waterResistance: '10 ATM', highlights: ['Leitura imediata', 'Proporção versátil', 'Espírito explorador'] },
  11: { story: 'Uma paleta de oliveiras e trilhas para quem encontra beleza nos detalhes simples do caminho.', movement: 'Automático', caseMaterial: 'Aço escovado', strap: 'Lona oliva', dial: 'Verde oliva', diameter: '39 mm', glass: 'Safira', waterResistance: '10 ATM', highlights: ['Visual utilitário', 'Leitura imediata', 'Uso cotidiano'] },
  12: { story: 'Uma segunda referência de horário acompanha seus deslocamentos, envolta em azul e aço.', movement: 'Automático GMT', caseMaterial: 'Aço escovado', strap: 'Couro azul', dial: 'Azul meia-noite', diameter: '41 mm', glass: 'Safira', waterResistance: '10 ATM', highlights: ['Segundo fuso', 'Ponteiro GMT', 'Horizontes abertos'] },
  13: { story: 'Uma leitura delicada do relógio de viagem, com tons suaves e a versatilidade de um segundo fuso.', movement: 'Automático GMT', caseMaterial: 'Aço com acabamento rosé', strap: 'Couro rosé', dial: 'Rosé suave', diameter: '39 mm', glass: 'Safira', waterResistance: '10 ATM', highlights: ['Segundo fuso', 'Paleta suave', 'Versatilidade'] },
  14: { story: 'Époque revisita as formas clássicas com um mostrador terracota que ganha vida sob a luz.', movement: 'Automático', caseMaterial: 'Aço polido', strap: 'Couro castanho', dial: 'Terracota', diameter: '38 mm', glass: 'Safira', waterResistance: '5 ATM', highlights: ['Inspiração vintage', 'Tons quentes', 'Perfil elegante'] },
}

export type Strap = { id: number; name: string; collection: string; material: 'Couro' | 'Borracha' | 'Lona' | 'Nylon' | 'Malha de aço' | 'Híbrida'; price: number; tone: string; color: string; widths: number[]; description: string; finish: string }
export const straps: Strap[] = [
  { id: 101, name: 'Atelier Cognac', collection: 'Linha Atelier', material: 'Couro', price: 390, tone: 'cognac', color: 'Conhaque', widths: [18, 20, 22], description: 'Couro de visual aquecido para mudar a expressão de um clássico.', finish: 'Fivela em aço polido' },
  { id: 102, name: 'Noir Suede', collection: 'Linha Atelier', material: 'Couro', price: 420, tone: 'suede', color: 'Preto', widths: [18, 20], description: 'Textura macia e elegância discreta para ocasiões especiais.', finish: 'Fivela em aço escovado' },
  { id: 103, name: 'Maré Azul', collection: 'Linha Performance', material: 'Borracha', price: 290, tone: 'aqua', color: 'Azul oceano', widths: [20, 22], description: 'Flexibilidade e cor para dias perto da água.', finish: 'Fivela em aço escovado' },
  { id: 104, name: 'Terrene Oliva', collection: 'Linha Explorer', material: 'Lona', price: 240, tone: 'khaki', color: 'Verde oliva', widths: [18, 20, 22], description: 'A textura do campo para um visual leve e versátil.', finish: 'Fivela em aço escovado' },
  { id: 105, name: 'Nato Terracota', collection: 'Linha Explorer', material: 'Nylon', price: 190, tone: 'rust', color: 'Terracota', widths: [18, 20], description: 'Uma faixa leve e expressiva para trocar de estilo em segundos.', finish: 'Ferragens em aço' },
  { id: 106, name: 'Milanese Prata', collection: 'Linha Studio', material: 'Malha de aço', price: 490, tone: 'silver', color: 'Prata', widths: [18, 20, 22], description: 'Malha metálica fluida com presença arquitetônica.', finish: 'Fecho deslizante em aço' },
  { id: 107, name: 'Sailcloth Grafite', collection: 'Linha Performance', material: 'Híbrida', price: 360, tone: 'slate', color: 'Grafite', widths: [20, 22], description: 'Textura técnica com interior flexível para acompanhar o ritmo.', finish: 'Fivela em aço escovado' },
]
export const strapFromPath = (pathname: string) => straps.find(strap => pathname === `/pulseiras/${slugOf(strap)}`) ?? null
