import { useMemo, useRef, useState } from 'react'
import { motion, useMotionValueEvent, useScroll, useTransform } from 'motion/react'
import { ArrowDown, ArrowRight, Plus, Ruler } from 'lucide-react'
import StrapVisual from './StrapVisual'
import { money, straps, type Strap } from './data'

const materials = ['Todos', 'Couro', 'Borracha', 'Lona', 'Nylon', 'Malha de aço', 'Híbrida'] as const

export default function StrapCatalog({ onOpen, onAdd }: { onOpen: (strap: Strap) => void; onAdd: (strap: Strap, width: number) => void }) {
  const [material, setMaterial] = useState<string>('Todos')
  const [width, setWidth] = useState<number | null>(null)
  const [scenePhase, setScenePhase] = useState(1)
  const sceneRef = useRef<HTMLElement>(null)
  const reduceMotion = false
  const { scrollYProgress } = useScroll({ target: sceneRef, offset: ['start start', 'end end'] })
  const sceneRotateY = useTransform(scrollYProgress, [0, .42, 1], [-50, 38, 315])
  const sceneRotateZ = useTransform(scrollYProgress, [0, .5, 1], [-16, 7, 21])
  const sceneScale = useTransform(scrollYProgress, [0, .5, 1], [.78, 1.12, .83])
  useMotionValueEvent(scrollYProgress, 'change', progress => setScenePhase(progress < .53 ? 1 : 2))
  const filtered = useMemo(() => straps.filter(strap => (material === 'Todos' || strap.material === material) && (width === null || strap.widths.includes(width))), [material, width])
  return <div className="strap-catalog">
    <section className="strap-hero"><div className="strap-hero-copy"><p className="eyebrow"><span className="eyebrow-line"/> AUREL / ACESSÓRIOS</p><h1>Um relógio.<br/><em>Novas histórias.</em></h1><p>Troque a pulseira. Reinvente a peça. Encontre a textura, a cor e o acabamento que acompanham cada versão de você.</p><button className="button button-light" onClick={() => document.getElementById('strap-products')?.scrollIntoView({ behavior: 'smooth' })}>Explorar pulseiras <ArrowRight size={18}/></button></div><div className="strap-hero-art"><div className="strap-hero-halo"/><motion.div className="strap-hero-object" initial={reduceMotion ? false : { opacity: 0, scale: .55, rotateY: -160, rotateZ: -22 }} animate={{ opacity: 1, scale: 1, rotateY: 360, rotateZ: 0 }} transition={{ duration: 2.1, ease: [.18, .68, .18, 1] }}><StrapVisual strap={straps[0]} large/></motion.div><span>01 / A EXPRESSÃO MUDA</span><div className="strap-hero-scroll">ROLE PARA DESCOBRIR <ArrowDown size={15}/></div></div></section>
    <section ref={sceneRef} className={`strap-scroll-scene ${reduceMotion ? 'reduced-motion' : ''}`} aria-label="Uma pulseira, novas perspectivas"><div className="strap-scene-sticky"><div className="strap-scene-outline strap-scene-outline-one"/><div className="strap-scene-outline strap-scene-outline-two"/><div className="strap-scene-wordmark" aria-hidden="true">TRANSFORME O TEMPO</div><motion.div className="strap-scene-object" style={reduceMotion ? undefined : { rotateY: sceneRotateY, rotateZ: sceneRotateZ, scale: sceneScale }}><StrapVisual strap={straps[2]} large/></motion.div><div className={`strap-scene-copy strap-scene-copy-first ${scenePhase === 1 ? 'is-active' : ''}`}><span>01 / TEXTURA</span><h2>Um detalhe.<br/><em>Outra energia.</em></h2><p>A mesma peça pode contar histórias diferentes.</p></div><div className={`strap-scene-copy strap-scene-copy-second ${scenePhase === 2 ? 'is-active' : ''}`}><span>02 / LIBERDADE</span><h2>Seu tempo.<br/><em>Seu estilo.</em></h2><p>Descubra materiais, cores e novas combinações.</p></div><div className="strap-scene-progress" aria-hidden="true"><motion.i style={reduceMotion ? undefined : { scaleX: scrollYProgress }}/></div><div className="strap-scene-caption">AUREL / UMA PEÇA, INFINITAS VERSÕES</div></div></section>
    <section id="strap-products" className="collection section-wrap strap-section"><div className="section-head"><div><p className="eyebrow dark"><span className="eyebrow-line"/> Encontre o seu encaixe</p><h2>Um detalhe.<br/><em>Outra perspectiva.</em></h2></div><p>Do couro à malha metálica, explore materiais para cada momento. Escolha a largura conforme o encaixe da caixa do seu relógio.</p></div><div className="strap-filter-tools"><div className="strap-materials" role="group" aria-label="Filtrar pulseiras por material">{materials.map(item => <button key={item} className={material === item ? 'active' : ''} onClick={() => setMaterial(item)}>{item}</button>)}</div><div className="strap-widths"><Ruler size={17}/><span>Largura</span>{[null, 18, 20, 22].map(item => <button key={item ?? 'all'} className={width === item ? 'active' : ''} onClick={() => setWidth(item)}>{item ? `${item} mm` : 'Todas'}</button>)}</div></div><p className="strap-count">{filtered.length} pulseiras encontradas</p><div className="product-grid strap-grid">{filtered.map((strap, index) => <motion.article className="product-card" key={strap.id} initial={{ opacity: 0, y: 28 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .05 }}><button className={`strap-card-art strap-art-${strap.tone}`} onClick={() => onOpen(strap)} aria-label={`Ver detalhes de ${strap.name}`}><span className="product-tag">{strap.material.toUpperCase()}</span><StrapVisual strap={strap}/><span className="view-product">Ver detalhes <ArrowRight size={15}/></span></button><div className="product-meta"><div><span>{strap.collection} · {strap.widths.join(' / ')} mm</span><h3><button className="product-name-link" onClick={() => onOpen(strap)}>{strap.name}</button></h3></div><strong>{money(strap.price)}</strong></div><button className="product-add" onClick={() => onAdd(strap, width && strap.widths.includes(width) ? width : strap.widths[0])}>Adicionar à sacola <Plus size={17}/></button></motion.article>)}</div>{filtered.length === 0 && <div className="empty-state">Nenhuma pulseira nessa combinação. Experimente outro material ou largura.</div>}</section>
    <section className="strap-guide"><span>GUIA DE ENCAIXE</span><h2>O tamanho certo<br/><em>faz toda a diferença.</em></h2><p>Antes de escolher, confira a largura entre as hastes da caixa do seu relógio. As opções 18, 20 e 22 mm indicam a largura da pulseira no ponto de encaixe.</p><a href="#strap-products">Encontrar minha pulseira <ArrowRight size={17}/></a></section>
  </div>
}
